#pragma once

#ifndef DYNAMIC_KEYMAP_LAYER_COUNT
    #define DYNAMIC_KEYMAP_LAYER_COUNT 3
#endif

#ifndef RGB_MATRIX_DEFAULT_MODE
    #define RGB_MATRIX_DEFAULT_MODE RGB_MATRIX_TYPING_HEATMAP
#endif

#if !defined(DOUBLE_TAP_SHIFT_TURNS_ON_CAPS_WORD) && defined(CAPS_WORD_ENABLE)
    #define DOUBLE_TAP_SHIFT_TURNS_ON_CAPS_WORD
#endif
